url: https://bright-softwares.com
#baseurl: /

# Site settings
title: Bright Softwares
logo: brightsoftwares-light.png
email: full@bright-softwares.com
description: "We provide solutions to our customers challenges. Our teams based in Paris and Lomé provide high value expertise to engineer the best solutions."


# Team names, titles and social links
people:
- name: Full Bright
  pic: 1
  position: AI solutions designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Kekeli Afanou
  pic: 2
  position: Cloud Nerd
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Christoli Wonegou
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/brightsoftwares
  - title: facebook
    url: http://fb.me/bright-softwares
  - title: stack-overflow
    url: #
  - title: github
    url: http://github.com/brightsoftwares

# Postal address (add as many lines as necessary)
address:
  - line: Quartier Attiegou, Togo 200
  - line: Lomé, Togo

# Build settings
markdown: kramdown
permalink: pretty